### ISSUE TITLE
提议

### ISSUE THREAD

**Issue by twocucao** [Surile/samle#1]

**Comment by twocucao** [comment]
@Surile 

简单分类没啥好玩的, 可以来一波后台识别

ref

https://github.com/alex2wong/trash-classify

**Comment by Surile** [comment]
@twocucao 没弄过啊。我就试试nestjs的框架。

**Comment by twocucao** [comment]
不复杂的, 就是调用一下包

**Comment by Surile** [comment]
@twocucao 有空看看下，你咋不说还有语音识别功能呢

**Comment by twocucao** [comment]
语音……也行吧 感觉垃圾分类用语音有点强行上识别的感觉

**Comment by Surile** [comment]
@twocucao 不知道。反正有人做了
