### ISSUE TITLE
没有数据库？

### ISSUE THREAD

**Issue by justmd5** [Surile/samle#3]
没有数据库结构？没看到对应的初始化操作的地方

**Comment by Surile** [comment]
@justmd5 数据库操作是使用的是`Typeorm`，在`ormconfig.json`配置文件中可以看到`synchronize `参数，代表每次启动是会自动创建表和库，数据库结构文件是`entities`参数所写的。

建议还是先看下[Typeorm](https://github.com/typeorm/typeorm)文档

**Comment by justmd5** [comment]
谢谢
